---
- hosts: planet-express
  name: Fetching and Tarring files

  tasks:
  - archive:
      path: /tmp/file1.txt
      dest: /tmp/file1.txt.gz
      format: gz
      
  - fetch:
      src: /tmp/file1.txt
      dest: /home/student/ansible/backup/
      

