---
- hosts: planet-express
  name: Fetching and Tarring files

  tasks:
  - archive:
      path: /tmp/file1.txt
      dest: /tmp/{{ ansible_date_time.date }}file1.txt.gz
      format: gz
  - debug:
      var: inventory_hostname
      
  - fetch:
      src: /tmp/{{ ansible_date_time.date }}file1.txt.gz 
      dest: /home/student/mycode/ansible/backup/
      

